const translations = {
    en: {
        greeting: "Game",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Phantom Freedom',
        community: 'Community',
        forum: 'Forum',
        discord: 'Discord',
        material: 'USEFUL MATERIALS',
        kankulator: 'Ability calculator',
        buket: 'Game booklet',
        accaunt: 'Accaunt',
        buy: 'Buy',
        sale: 'Already on sale',
        buys: 'Buy',
        treyler: 'TREYLER',
        change: 'en',
        en: 'English',
        ru: 'Russia',
        de: 'German',
        po: 'Polish',
        pr: 'Portuguese (BR)',
        fr: 'French',
        es: 'Spanish',
        esp: 'Spanish (MX)',
        it: 'Italian',
        ja: 'Japanese',
        ko: 'Korean',
        ch: 'Simplified Chinese',
        chs: 'Traditional Chinese',
        ar: 'Arabic',
        open: 'LOGIN',
        free: 'Play for free',
        firstinput : 'E-mail',
        secondinput : 'Password',
        recovery: 'reset password',
        create: 'create an account',
        option: 'select a language',
        mailinput: 'Email address',
        nameinput: 'Name',
        surnameinput: 'Surename',
        returnname: 'Display name',
        textpasswordss: 'password',
        submitbtn: 'continue',
        popuptitle: 'create an account',
        radiopteg: 'Contact me for news, surveys and special offers from Epic Games',
        radiopp: 'I have read and accept , terms of service',
        radilink: 'terms of service',

        popupt: 'lorem',
        conectp: 'aerg',
        openss: 'Choo',
        loginbutton: 'earg'
    },
    ru: {
        greeting: "Игры",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Призрачная свобода',
        community: 'Сообщество',
        forum: 'Форум',
        discord: 'Discord',
        material: 'ПОЛЕЗНЫЕ МАТЕРИАЛЫ',
        kankulator: 'Калькулятор способностей',
        buket: 'Игровой буклет',
        accaunt: 'Aккаунт',
        buy: 'Купить',
        sale: 'Уже в продаже',
        buys: 'Купить',
        treyler: 'ТРЕЙЛЕР',
        change: 'ru',
        en: 'Английский',
        ru: 'Россия',
        de: 'немецкий',
        po: 'польский',
        pr: 'португальский (BR)',
        fr: 'Французский',
        es: 'испанский',
        esp: 'испанский (MX)',
        it: 'итальянский',
        ja: 'японский',
        ko: 'корейский',
        ch: 'Упрощенный к',
        chs: 'Традиционный к',
        ar: 'арабский',
        open: 'ВОЙТИ',
        free: 'Играйте бесплатно',
        firstinput : 'Электронная почта',
        secondinput : 'Пароль',
        recovery: 'сброс пароля ',
        create: 'создать учётную запись',

    },
    de: {
        greeting: "Spiele",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Phantomfreiheit',
        community: 'Gemeinschaft',
        forum: 'Forum',
        discord: 'Zwietracht',
        material: 'NÜTZLICHE MATERIALIEN',
        kankulator: 'Fähigkeitsrechner',
        buket: 'Spielheft',
        accaunt: 'Konto',
        buy: 'Kaufen',
        sale: 'Bereits im Verkauf',
        buys: 'Kaufen',
        treyler: 'ANHÄNGER',
        change: 'De',  
        en: 'Englisch',
        ru: 'Russland',
        de: 'Deutsch',
        po: 'Polieren',
        pr: 'Portugiesisch (BR)',
        fr: 'Französisch',
        es: 'Spanisch',
        esp: 'Spanisch (MX)',
        it: 'Italienisch',
        ja: 'japanisch',
        ko: 'Koreanisch',
        ch: 'Vereinfachtes Ch',
        chs: 'Traditionelles Ch',
        ar: 'Arabisch',
        open: 'offen',
        free: 'Kostenlos spielen',
        firstinput: 'E-Mail',
        secondinput: 'Passwort',
        recovery: 'Passwort zurücksetzen',
        create: 'ein Konto erstellen',

    },
    pl: {
        greeting: "Gra",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Fantomowa wolność',
        community: 'Wspólnota',
        forum: 'Forum',
        discord: 'Niezgoda',
        material: 'MATERIAŁY PRZYDATNE',
        kankulator: 'Kalkulator umiejętności',
        buket: 'Broszura gry',
        accaunt: 'Konto',
        buy: 'Kupić',
        sale: 'Już w sprzedaży',
        buys: 'Kupić',
        treyler: 'TREYLER',
        change: 'Pl',
        en: 'angielski',
        ru: 'Rosja',
        de: 'niemiecki',
        po: 'Polski',
        pr: 'portugalski (BR)',
        fr: 'francuski',
        es: 'hiszpański',
        esp: 'hiszpański (MX)',
        it: 'włoski',
        ja: 'japoński',
        ko: 'koreański',
        ch: 'uproszczony ch',
        chs: 'Tradycyjny ch',
        ar: 'arabski',
        open: 'OTWARTE',
        free: 'Graj za darmo',
        firstinput: 'E-mail',
        secondinput: 'Hasło',
        recovery: 'zresetuj hasło',
        create: 'Utwórz konto',

    },
    ptBr: {
        greeting: "Jogo",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Liberdade Fantasma',
        community: 'Comunidade',
        forum: 'Fórum',
        discord: 'Discórdia',
        material: 'MATERIAIS ÚTEIS',
        kankulator: 'Calculadora de habilidade',
        buket: 'Livreto do jogo',
        accaunt: 'Conta',
        buy: 'Comprar',
        sale: 'Já à venda',
        buys: 'Comprar',
        treyler: 'Treyler-Antônio',
        change: 'PT',
        en: 'Inglês',
        ru: 'Rússia',
        de: 'Alemã',
        po: 'Polonês',
        pr: 'Português (BR)',
        fr: 'Francesa',
        es: 'Espanhola',
        esp: 'Espanhola (MX)',
        it: 'Italiana',
        ja: 'japonês',
        ko: 'Coreana',
        ch: 'Chinês s',
        chs: 'Chinês t',
        ar: 'árabe',
        open: 'ABRIR',
        free: 'Jogue de graça',
        firstinput: 'e-mail',
        secondinput: 'Senha',
        recovery: 'redefinir senha',
        create: 'Criar uma conta',

    },
    fr: {
        greeting: "Jeu",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Liberté fantôme',
        community: 'Communauté',
        forum: 'Forum',
        discord: 'Discorde',
        material: 'MATÉRIAUX UTILES',
        kankulator: 'Calculateur de capacité',
        buket: 'Livret de jeu',
        accaunt: 'Compte',
        buy: 'Acheter',
        sale: 'Déjà en vente',
        buys: 'Acheter',
        treyler: 'TREYLER', 
        change: 'fr',
        en: 'Anglaise',
        ru: 'Russie',
        de: 'germany',
        po: 'polonais',
        pr: 'portugais (BR)',
        fr: 'Français',
        es: 'spanish',
        esp: 'Spanish (MX)',
        it: 'Italienne',
        ja: 'japanese',
        ko: 'Coréenne',
        ch: 'Chinois s',
        chs: 'Chinois t',
        ar: 'arabe',
        open: 'OUVRIR',
        free: 'Jouer gratuitement',
        firstinput: 'Entrez une adresse e-mail',
        secondinput: 'Mot de passe',
        recovery: 'réinitialiser le mot de passe',
        create: 'créer un compte',

    },
    es: {
        greeting: "Juego",
        fravel: 'Ciberpunk 2077',
        fravel2: 'Libertad fantasma',
        community: 'Comunidad',
        forum: 'Foro',
        discord: 'Discordia',
        material: 'MATERIALES ÚTILES',
        kankulator: 'Calculadora de habilidades',
        buket: 'Folleto del juego',
        accaunt: 'Cuenta',
        buy: 'Comprar',
        sale: 'Ya a la venta',
        buys: 'Comprar',
        treyler: 'Treyler',
        change: 'Es',
        en: 'Inglesa',
        ru: 'Rusia',
        de: 'germany',
        po: 'Polaca',
        pr: 'Portuguesa (BR)',
        fr: 'Francesa',
        es: 'Española',
        esp: 'Española (MX)',
        it: 'Italiana',
        ja: 'Japonesa',
        ko: 'Coreana',
        ch: 'Chino s',
        chs: 'Chino t',
        ar: 'árabe',
        open: 'ABIERTO',
        free: 'Jugar gratis',
        firstinput: 'Introduce tu correo electrónico',
        secondinput: 'contraseña',
        recovery: 'restablecer contraseña',
        create: 'Crear una cuenta',

    },
    esMx: {
        greeting: "Juego",
        fravel: 'Ciberpunk 2077',
        fravel2: 'Libertad fantasma',
        community: 'Comunidad',
        forum: 'Foro',
        discord: 'Discordia',
        material: 'MATERIALES ÚTILES',
        kankulator: 'Calculadora de habilidades',
        buket: 'Folleto del juego',
        accaunt: 'Cuenta',
        buy: 'Comprar',
        sale: 'Ya a la venta',
        buys: 'Comprar',
        treyler: 'Treyler',
        change: 'Es (MX)',
        en: 'Inglesa',
        ru: 'Rusia',
        de: 'germany',
        po: 'Polaca',
        pr: 'Portuguesa (BR)',
        fr: 'Francesa',
        es: 'Española',
        esp: 'Española (MX)',
        it: 'Italiana',
        ja: 'Japonesa',
        ko: 'Coreana',
        ch: 'Chino s',
        chs: 'Chino t',
        ar: 'árabe',
        open: 'ABIERTO',
        free: 'Jugar gratis',
        firstinput: 'Introduce tu correo electrónico',
        secondinput: 'contraseña',
        recovery: 'restablecer contraseña',
        create: 'Crear una cuenta',

    },
    it: {
        greeting: "gioco",
        fravel: 'Il cyberpunk 2077',
        fravel2: 'Libertà fantasma',
        community: 'Comunità',
        forum: 'Foro',
        discord: 'Discordia',
        material: 'MATERIALI UTILI',
        kankulator: 'Calcolatrice di capacità',
        buket: 'Libretto del gioco',
        accaunt: 'Account',
        buy: 'Acquistare',
        sale: 'Già in vendita',
        buys: 'Acquistare',
        treyler: 'TREYLER',
        change: 'It',
        en: 'Inglese',
        ru: 'Russia',
        de: 'Tedesca',
        po: 'Polacca',
        pr: 'portoghese (BR)',
        fr: 'francese',
        es: 'Spangola',
        esp: 'Spangola (MX)',
        it: 'Italiana',
        ja: 'giapponese',
        ko: 'Coreana',
        ch: 'Cinese s',
        chs: 'Cinese t',
        ar: 'Araba',
        open: 'APRIRE',
        free: 'Gioca gratis',
        firstinput: 'Inserisci la tua email',
        secondinput: 'password',
        recovery: 'Reimposta password',
        create: 'creare un account',

    },
    ja: {
        greeting: "ゲーム",
        fravel: 'サイバーパンク2077',
        fravel2: 'ファントムフリーダム',
        community: 'コミュニティ',
        forum: 'フォーラム',
        discord: '不和',
        material: '役に立つ資料',
        kankulator: '能力計算機',
        buket: 'ゲームブックレット',
        accaunt: 'アカウント',
        buy: '買う',
        sale: 'すでに販売中',
        buys: '買う',
        treyler: 'トレイラー',
        change: '日本語',
        en: '英語',
        ru: 'ロシア',
        de: 'ドイツ語',
        po: '研磨',
        pr: 'ポルトガル語（BR）',
        fr: 'フランス語',
        es: 'スペイン語',
        esp: 'スペイン語 (MX)',
        it: 'イタリア語',
        ja: '日本語',
        ko: '韓国語',
        ch: '中国語（簡体字）',
        chs: '繁体字中国語',
        ar: 'アラビア語',
        open: '開ける',
        free: '無料でプレイ',
        firstinput: 'メールアドレスを入力してください',
        secondinput: 'パスワード',
        recovery: 'パスワードをリセット',
        create: 'アカウントを作成する',

    },
    ko: {
        greeting: "게임",
        fravel: '사이버펑크 2077',
        fravel2: '팬텀 프리덤',
        community: '지역 사회',
        forum: '법정',
        discord: '불화',
        material: '유용한 자료',
        kankulator: '능력 계산기',
        buket: '게임 소책자',
        accaunt: '계정',
        buy: '구입하다',
        sale: '이미 판매중입니다',
        buys: '구입하다',
        treyler: '트레이러',
        change: '한국어',
        en: '영어',
        ru: '러시아 제국',
        de: '독일 사람',
        po: '광택',
        pr: '포르투갈어(BR)',
        fr: '프랑스 국민',
        es: '스페인 사람',
        esp: '스페인 사람 (MX)',
        it: '이탈리아 사람',
        ja: '일본어',
        ko: '한국인',
        ch: '간체 중국어',
        chs: '중국어 번체',
        ar: '아라비아 말',
        open: '열려 있는',
        free: '무료로 플레이하세요',
        firstinput: '이메일을 입력하세요',
        secondinput: '비밀번호',
        recovery: '비밀번호 재설정',
        create: '계정을 생성하다',

    },
    zhCn: {
        greeting: "游戏",
        fravel: '赛博朋克 2077',
        fravel2: '幻影自由',
        community: '社区',
        forum: '论坛',
        discord: '不和谐',
        material: '有用资料',
        kankulator: '能力计算器',
        buket: '游戏手册',
        accaunt: '帐户',
        buy: '买',
        sale: '已开始销售',
        buys: '买',
        treyler: '特雷勒', 
        change: '简体中文',
        en: '英语',
        ru: '俄罗斯',
        de: '德语',
        po: '抛光',
        pr: '葡萄牙语 （巴西）',
        fr: '法语',
        es: '西班牙语',
        esp: '西班牙语',
        it: '意大利语',
        ja: '日本人',
        ko: '韩国人',
        ch: '简体中文',
        chs: '繁体中文',
        ar: '阿拉伯',
        open: '打开',
        free: '免费畅玩',
        firstinput: '输入您的电子邮件',
        secondinput: '输入您的密码',
        recovery: '重置密码',
        create: '创建一个帐户',

    },
    zhtw: {
        greeting: "游戏",
        fravel: '赛博朋克 2077',
        fravel2: '幻影自由',
        community: '社区',
        forum: '论坛',
        discord: '不和谐',
        material: '有用资料',
        kankulator: '能力计算器',
        buket: '游戏手册',
        accaunt: '帐户',
        buy: '买',
        sale: '已开始销售',
        buys: '买',
        treyler: '特雷勒',
        change: '繁體中文',
        en: '英語',
        ru: '俄羅斯',
        de: '德文',
        po: '拋光',
        pr: '葡萄牙語（巴西）',
        fr: '法語',
        es: '西班牙語',
        esp: '西班牙語 (MX)',
        it: '義大利語',
        ja: '日本人',
        ko: '韓國人',
        ch: '簡體中文',
        chs: '繁體中文',
        ar: '阿拉伯',
        open: '打开',
        free: '免费畅玩',
        firstinput: '输入您的电子邮件',
        secondinput: '输入您的密码',
        recovery: '重置密码',
        create: '创建一个帐户',

    },
    ar: {
        greeting: "لعبة",
        fravel: 'السايبربانك 2077',
        fravel2: 'الحرية الشبحية',
        community: 'مجتمع',
        forum: 'المنتدى',
        discord: 'الخلاف',
        material: 'مواد مفيدة',
        kankulator: 'حاسبة القدرة',
        buket: 'كتيب اللعبة',
        accaunt: 'حساب',
        buy: 'يشتري',
        sale: 'معروض للبيع بالفعل',
        buys: 'يشتري',
        treyler: 'تريلر',
        change: 'العربية',
        en: 'إنجليزي',
        ru: 'روسيا',
        de: 'الألمانية',
        po: 'بولندي',
        pr: 'البرتغالية (البرازيل)',
        fr: 'فرنسي',
        es: 'الأسبانية',
        esp: 'الإسبانية (المكسيك)',
        it: 'ايطالي',
        ja: 'اليابانية',
        ko: 'كوري',
        ch: 'الصينية المبسطة',
        chs: 'الصينية التقليدية',
        ar: 'عربي',
        open: 'يفتح',
        free: 'العب مجانا',
        firstinput: 'أدخل بريدك الإلكتروني',
        secondinput: 'أدخل كلمة المرور الخاصة بك',
        recovery: 'إعادة تعيين كلمة المرور',
        create: 'إنشاء حساب',
        radiopteg: 'Contact me for news, surveys and special offers from Epic Games',
        radiopp: 'I have read and accept',
        radilink: 'terms of service',
        

    }
};

let currentLanguage = 'en';

function setLanguage(lang) {
    currentLanguage = lang;
    updateUI();
}

function updateUI() {
    document.getElementById('greeting').innerText = translations[currentLanguage].greeting;
    document.getElementById('farewell').innerHTML = translations[currentLanguage].fravel;
    document.getElementById('fravel2').innerHTML = translations[currentLanguage].fravel2;
    document.getElementById('community').innerHTML = translations[currentLanguage].community;
    document.getElementById('forum').innerHTML = translations[currentLanguage].forum;
    document.getElementById('discord').innerHTML = translations[currentLanguage].discord;
    document.getElementById('material').innerHTML = translations[currentLanguage].material;
    document.getElementById('kankulator').innerHTML = translations[currentLanguage].kankulator;
    document.getElementById('buket').innerHTML = translations[currentLanguage].buket;
    document.getElementById('accaunt').innerHTML = translations[currentLanguage].accaunt;
    document.getElementById('buy').innerHTML = translations[currentLanguage].buy;
    document.getElementById('sale').innerHTML = translations[currentLanguage].sale;
    document.getElementById('buys').innerHTML = translations[currentLanguage].buys;
    document.getElementById('treyler').innerHTML = translations[currentLanguage].treyler;
    document.getElementById('change').innerHTML = translations[currentLanguage].change;
    document.getElementById('en').innerHTML = translations[currentLanguage].en;
    document.getElementById('ru').innerHTML = translations[currentLanguage].ru;
    document.getElementById('de').innerHTML = translations[currentLanguage].de;
    document.getElementById('po').innerHTML = translations[currentLanguage].po;
    document.getElementById('pr').innerHTML = translations[currentLanguage].pr;
    document.getElementById('fr').innerHTML = translations[currentLanguage].fr;
    document.getElementById('es').innerHTML = translations[currentLanguage].es;
    document.getElementById('esp').innerHTML = translations[currentLanguage].esp;
    document.getElementById('it').innerHTML = translations[currentLanguage].it;
    document.getElementById('ja').innerHTML = translations[currentLanguage].ja;
    document.getElementById('ko').innerHTML = translations[currentLanguage].ko;
    document.getElementById('ch').innerHTML = translations[currentLanguage].ch;
    document.getElementById('chs').innerHTML = translations[currentLanguage].chs;
    document.getElementById('ar').innerHTML = translations[currentLanguage].ar;
    document.getElementById('open').innerHTML = translations[currentLanguage].open;
    document.getElementById('opens').innerHTML = translations[currentLanguage].open;
    document.getElementById('free').innerHTML = translations[currentLanguage].free;
    document.getElementById('textgmail').placeholder = translations[currentLanguage].firstinput;
    document.getElementById('textpassword').placeholder = translations[currentLanguage].secondinput;
    document.getElementById('textpasswordss').placeholder = translations[currentLanguage].secondinput;
    document.getElementById('recovery').innerHTML = translations[currentLanguage].recovery;
    document.getElementById('createAccount').innerHTML = translations[currentLanguage].create;
    
    document.getElementById('radiopteg').innerHTML = translations[currentLanguage].radiopteg;
    document.getElementById('radiopp').innerHTML = translations[currentLanguage].radiopp;
    document.getElementById('radiolink').innerHTML = translations[currentLanguage].radiolink;
    document.getElementById('popuptitle').innerHTML = translations[currentLanguage].popuptitle;
    document.getElementById('option').innerHTML = translations[currentLanguage].option;
    document.getElementById('mailinput').placeholder = translations[currentLanguage].mailinput;
    document.getElementById('nameinput').placeholder = translations[currentLanguage].nameinput;
    document.getElementById('surnameinput').placeholder = translations[currentLanguage].surnameinput;
    document.getElementById('returnname').placeholder = translations[currentLanguage].returnname;
    document.getElementById('radilink').innerHTML = translations[currentLanguage].radilink;
}



window.onload = updateUI;