const translations = {
    en: {
        greeting: "Game",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Phantom Freedom',
        community: 'Community',
        forum: 'Forum',
        discord: 'Discord',
        material: 'USEFUL MATERIALS',
        kankulator: 'Ability calculator',
        buket: 'Game booklet',
        accaunt: 'Accaunt',
        buy: 'Buy',
        sale: 'Already on sale',
        buys: 'Buy',
        treyler: 'TREYLER',
        change: 'en',
        en: 'English',
        ru: 'Russia',
        de: 'German',
        po: 'Polish',
        pr: 'Portuguese (BR)',
        fr: 'French',
        es: 'Spanish',
        esp: 'Spanish (MX)',
        it: 'Italian',
        ja: 'Japanese',
        ko: 'Korean',
        ch: 'Simplified Chinese',
        chs: 'Traditional Chinese',
        ar: 'Arabic',
        open: 'LOGIN',
        free: 'Play for free',
        firstinput : 'E-mail',
        secondinput : 'Password',
        recovery: 'reset password',
        create: 'create an account',
        popuptitle: 'Create an account',
        option: 'Chooise language...',
        mailinput: 'E-mail',
        nameinput: 'Name',
        textpasswordss: 'password',
        surnameinput: 'Surname',
        returnname: 'Display name',
        radiop: 'Send me news, surveys and special offers from Cypernet Games',
        radiopp: 'I have read and accept , terms of service',
        radiolink: 'terms of service',
        submitbtn: 'continue',
        popupt: 'Reset password',
        conectp: 'To receive a security code, please enter the email address of your Cypernet Games account',
        openss: 'Continue',
        loginbutton: 'return to login page',
        successMessage: 'Successful!',
        fillFields: 'Please fill in all fields.',
        
    },
    ru: {
        greeting: "Игры",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Призрачная свобода',
        community: 'Сообщество',
        forum: 'Форум',
        discord: 'Discord',
        material: 'ПОЛЕЗНЫЕ МАТЕРИАЛЫ',
        kankulator: 'Калькулятор способностей',
        buket: 'Игровой буклет',
        accaunt: 'Aккаунт',
        buy: 'Купить',
        sale: 'Уже в продаже',
        buys: 'Купить',
        treyler: 'ТРЕЙЛЕР',
        change: 'ru',
        en: 'Английский',
        ru: 'Россия',
        de: 'немецкий',
        po: 'польский',
        pr: 'португальский (BR)',
        fr: 'Французский',
        es: 'испанский',
        esp: 'испанский (MX)',
        it: 'итальянский',
        ja: 'японский',
        ko: 'корейский',
        ch: 'Упрощенный к',
        chs: 'Традиционный к',
        ar: 'арабский',
        open: 'ВОЙТИ',
        free: 'Играйте бесплатно',
        firstinput : 'Электронная почта',
        secondinput : 'Пароль',
        recovery: 'сброс пароля ',
        create: 'создать учётную запись',
        popuptitle: 'Завести аккаунт',
        option: 'Выберите язык...',
        mailinput: 'Электронная почта',
        nameinput: 'Имя',
        textpasswordss: 'пароль',
        surnameinput: 'Фамилия',
        returnname: 'Отображаемое имя',
        radiop: 'Присылайте мне новости, опросы и специальные предложения от Cybernet Games',
        radiopp: 'Я прочитал(а) и принимаю условия обслуживания',
        radiolink: 'условия обслуживания',
        submitbtn: 'продолжать',
        popupt: 'Сбросить пароль',
        conectp: 'Чтобы получить код безопасности, введите адрес электронной почты вашей учетной записи Cybernet Games.',
        openss: 'продолжать',
        loginbutton: 'вернуться на страницу входа',
        successMessage: 'Успешный!',
        fillFields: 'Пожалуйста, заполните все поля.',
    },
    de: {
        greeting: "Spiele",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Phantomfreiheit',
        community: 'Gemeinschaft',
        forum: 'Forum',
        discord: 'Zwietracht',
        material: 'NÜTZLICHE MATERIALIEN',
        kankulator: 'Fähigkeitsrechner',
        buket: 'Spielheft',
        accaunt: 'Konto',
        buy: 'Kaufen',
        sale: 'Bereits im Verkauf',
        buys: 'Kaufen',
        treyler: 'ANHÄNGER',
        change: 'De',  
        en: 'Englisch',
        ru: 'Russland',
        de: 'Deutsch',
        po: 'Polieren',
        pr: 'Portugiesisch (BR)',
        fr: 'Französisch',
        es: 'Spanisch',
        esp: 'Spanisch (MX)',
        it: 'Italienisch',
        ja: 'japanisch',
        ko: 'Koreanisch',
        ch: 'Vereinfachtes Ch',
        chs: 'Traditionelles Ch',
        ar: 'Arabisch',
        open: 'offen',
        free: 'Kostenlos spielen',
        firstinput: 'E-Mail',
        secondinput: 'Passwort',
        recovery: 'Passwort zurücksetzen',
        create: 'ein Konto erstellen',
        popuptitle: 'Ein Konto erstellen',
        option: 'Sprache auswählen...',
        mailinput: 'E-Mail',
        nameinput: 'Name',
        textpasswordss: 'passwort',
        surnameinput: 'Nachname',
        returnname: 'Anzeigename',
        radiop: 'Senden Sie mir Neuigkeiten, Umfragen und Sonderangebote von Cypernet Games',
        radiopp: 'Ich habe die Servicebedingungen gelesen und akzeptiere sie.',
        radiolink: 'Servicebedingungen',
        submitbtn: 'weitermachen',
        popupt: 'Passwort zurücksetzen',
        conectp: 'Um einen Sicherheitscode zu erhalten, geben Sie bitte die E-Mail-Adresse Ihres Cypernet Games-Kontos ein',
        openss: 'weitermachen',
        loginbutton: 'zurück zur Login-Seite',
        successMessage: 'Erfolgreich!',
        fillFields: 'Bitte füllen Sie alle Felder aus.',
    },
    pl: {
        greeting: "Gra",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Fantomowa wolność',
        community: 'Wspólnota',
        forum: 'Forum',
        discord: 'Niezgoda',
        material: 'MATERIAŁY PRZYDATNE',
        kankulator: 'Kalkulator umiejętności',
        buket: 'Broszura gry',
        accaunt: 'Konto',
        buy: 'Kupić',
        sale: 'Już w sprzedaży',
        buys: 'Kupić',
        treyler: 'TREYLER',
        change: 'Pl',
        en: 'angielski',
        ru: 'Rosja',
        de: 'niemiecki',
        po: 'Polski',
        pr: 'portugalski (BR)',
        fr: 'francuski',
        es: 'hiszpański',
        esp: 'hiszpański (MX)',
        it: 'włoski',
        ja: 'japoński',
        ko: 'koreański',
        ch: 'uproszczony ch',
        chs: 'Tradycyjny ch',
        ar: 'arabski',
        open: 'OTWARTE',
        free: 'Graj za darmo',
        firstinput: 'E-mail',
        secondinput: 'Hasło',
        recovery: 'zresetuj hasło',
        create: 'Utwórz konto',
        popuptitle: 'Utwórz konto',
        option: 'Wybierz język...',
        mailinput: 'E-mail',
        nameinput: 'Nazwa',
        textpasswordss: 'hasło',
        surnameinput: 'Nazwisko',
        returnname: 'Nazwa wyświetlana',
        radiop: 'Wyślij mi wiadomości, ankiety i oferty specjalne od Cypernet Games',
        radiopp: 'Przeczytałem i akceptuję regulamin usługi',
        radiolink: 'warunki korzystania z usługi',
        submitbtn: 'Kontynuować',
        popupt: 'Zresetuj hasło',
        conectp: 'Aby otrzymać kod bezpieczeństwa, wprowadź adres e-mail swojego konta Cybernet Games',
        openss: 'Kontynuować',
        loginbutton: 'powrót do strony logowania',
        successMessage: 'Udany!',
        fillFields: 'Proszę wypełnić wszystkie pola.',
    },
    ptBr: {
        greeting: "Jogo",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Liberdade Fantasma',
        community: 'Comunidade',
        forum: 'Fórum',
        discord: 'Discórdia',
        material: 'MATERIAIS ÚTEIS',
        kankulator: 'Calculadora de habilidade',
        buket: 'Livreto do jogo',
        accaunt: 'Conta',
        buy: 'Comprar',
        sale: 'Já à venda',
        buys: 'Comprar',
        treyler: 'Treyler-Antônio',
        change: 'PT',
        en: 'Inglês',
        ru: 'Rússia',
        de: 'Alemã',
        po: 'Polonês',
        pr: 'Português (BR)',
        fr: 'Francesa',
        es: 'Espanhola',
        esp: 'Espanhola (MX)',
        it: 'Italiana',
        ja: 'japonês',
        ko: 'Coreana',
        ch: 'Chinês s',
        chs: 'Chinês t',
        ar: 'árabe',
        open: 'ABRIR',
        free: 'Jogue de graça',
        firstinput: 'e-mail',
        secondinput: 'Senha',
        recovery: 'redefinir senha',
        create: 'Criar uma conta',
        popuptitle: 'Criar uma conta',
        option: 'Escolha o idioma...',
        mailinput: 'E-mail',
        nameinput: 'Nome',
        textpasswordss: 'senha',
        surnameinput: 'Sobrenome',
        returnname: 'Nome de exibição',
        radiop: 'Envie-me notícias, pesquisas e ofertas especiais da Cybernet Games',
        radiopp: 'Li e aceito os termos de serviço',
        radiolink: 'termos de serviço',
        submitbtn: 'continuar',
        popupt: 'Redefinir senha',
        conectp: 'Para receber um código de segurança, insira o endereço de e-mail da sua conta Cybernet Games',
        openss: 'continuar',
        loginbutton: 'retornar para a página de login',
        successMessage: 'Bem-sucedida!',
        fillFields: 'Por favor, preencha todos os campos.',
    },
    fr: {
        greeting: "Jeu",
        fravel: 'Cyberpunk 2077',
        fravel2: 'Liberté fantôme',
        community: 'Communauté',
        forum: 'Forum',
        discord: 'Discorde',
        material: 'MATÉRIAUX UTILES',
        kankulator: 'Calculateur de capacité',
        buket: 'Livret de jeu',
        accaunt: 'Compte',
        buy: 'Acheter',
        sale: 'Déjà en vente',
        buys: 'Acheter',
        treyler: 'TREYLER', 
        change: 'fr',
        en: 'Anglaise',
        ru: 'Russie',
        de: 'germany',
        po: 'polonais',
        pr: 'portugais (BR)',
        fr: 'Français',
        es: 'spanish',
        esp: 'Spanish (MX)',
        it: 'Italienne',
        ja: 'japanese',
        ko: 'Coréenne',
        ch: 'Chinois s',
        chs: 'Chinois t',
        ar: 'arabe',
        open: 'OUVRIR',
        free: 'Jouer gratuitement',
        firstinput: 'Entrez une adresse e-mail',
        secondinput: 'Mot de passe',
        recovery: 'réinitialiser le mot de passe',
        create: 'créer un compte',
        popuptitle: 'Créer un compte',
        option: 'Choisissez la langue...',
        mailinput: 'E-mail',
        nameinput: 'Nom',
        textpasswordss: 'mot de passe',
        surnameinput: 'Nom de famille',
        returnname: `Nom d'affichage`,
        radiop: 'Envoyez-moi des nouvelles, des sondages et des offres spéciales de Cypernet Games',
        radiopp: `J'ai lu et j'accepte les conditions d'utilisation`,
        radiolink: `conditions d'utilisation`,
        submitbtn: 'continuer',
        popupt: 'Réinitialiser le mot de passe',
        conectp: `Pour recevoir un code de sécurité, veuillez saisir l'adresse e-mail de votre compte Cypernet Games`,
        openss: 'continuer',
        loginbutton: 'retour à la page de connexion',
        successMessage: 'Réussie!',
        fillFields: 'Veuillez remplir tous les champs.',
    },
    es: {
        greeting: "Juego",
        fravel: 'Ciberpunk 2077',
        fravel2: 'Libertad fantasma',
        community: 'Comunidad',
        forum: 'Foro',
        discord: 'Discordia',
        material: 'MATERIALES ÚTILES',
        kankulator: 'Calculadora de habilidades',
        buket: 'Folleto del juego',
        accaunt: 'Cuenta',
        buy: 'Comprar',
        sale: 'Ya a la venta',
        buys: 'Comprar',
        treyler: 'Treyler',
        change: 'Es',
        en: 'Inglesa',
        ru: 'Rusia',
        de: 'germany',
        po: 'Polaca',
        pr: 'Portuguesa (BR)',
        fr: 'Francesa',
        es: 'Española',
        esp: 'Española (MX)',
        it: 'Italiana',
        ja: 'Japonesa',
        ko: 'Coreana',
        ch: 'Chino s',
        chs: 'Chino t',
        ar: 'árabe',
        open: 'ABIERTO',
        free: 'Jugar gratis',
        firstinput: 'Introduce tu correo electrónico',
        secondinput: 'contraseña',
        recovery: 'restablecer contraseña',
        create: 'Crear una cuenta',
        popuptitle: 'Crear una cuenta',
        option: 'Elija idioma...',
        mailinput: 'Correo electrónico',
        nameinput: 'Nombre',
        textpasswordss: 'contraseña',
        surnameinput: 'Apellido',
        returnname: 'Nombre para mostrar',
        radiop: 'Envíame noticias, encuestas y ofertas especiales de Cypernet Gamesa',
        radiopp: 'He leído y acepto los términos del servicio',
        radiolink: 'Condiciones del servicio',
        submitbtn: 'continuar',
        popupt: 'Restablecer contraseña',
        conectp: 'Para recibir un código de seguridad, ingrese la dirección de correo electrónico de su cuenta de Cypernet Games',
        openss: 'continuar',
        loginbutton: 'volver a la página de inicio de sesión',
        successMessage: 'Exitosa!',
        fillFields: 'Por favor, rellene todos los campos.',
    },
    esMx: {
        greeting: "Juego",
        fravel: 'Ciberpunk 2077',
        fravel2: 'Libertad fantasma',
        community: 'Comunidad',
        forum: 'Foro',
        discord: 'Discordia',
        material: 'MATERIALES ÚTILES',
        kankulator: 'Calculadora de habilidades',
        buket: 'Folleto del juego',
        accaunt: 'Cuenta',
        buy: 'Comprar',
        sale: 'Ya a la venta',
        buys: 'Comprar',
        treyler: 'Treyler',
        change: 'Es (MX)',
        en: 'Inglesa',
        ru: 'Rusia',
        de: 'germany',
        po: 'Polaca',
        pr: 'Portuguesa (BR)',
        fr: 'Francesa',
        es: 'Española',
        esp: 'Española (MX)',
        it: 'Italiana',
        ja: 'Japonesa',
        ko: 'Coreana',
        ch: 'Chino s',
        chs: 'Chino t',
        ar: 'árabe',
        open: 'ABIERTO',
        free: 'Jugar gratis',
        firstinput: 'Introduce tu correo electrónico',
        secondinput: 'contraseña',
        recovery: 'restablecer contraseña',
        create: 'Crear una cuenta',
        popuptitle: 'Crear una cuenta',
        option: 'Elija idioma...',
        mailinput: 'Correo electrónico',
        nameinput: 'Nombre',
        textpasswordss: 'contraseña',
        surnameinput: 'Apellido',
        returnname: 'Nombre para mostrar',
        radiop: 'Envíame noticias, encuestas y ofertas especiales de Cypernet Games',
        radiopp: 'He leído y acepto los términos del servicio',
        radiolink: 'Condiciones del servicio',
        submitbtn: 'continuar',
        popupt: 'Restablecer contraseña',
        conectp: 'Para recibir un código de seguridad, ingrese la dirección de correo electrónico de su cuenta de Cypernet Games',
        openss: 'continuar',
        loginbutton: 'volver a la página de inicio de sesión',
        successMessage: 'Exitosa!',
        fillFields: 'Por favor, rellene todos los campos.',
    },
    it: {
        greeting: "gioco",
        fravel: 'Il cyberpunk 2077',
        fravel2: 'Libertà fantasma',
        community: 'Comunità',
        forum: 'Foro',
        discord: 'Discordia',
        material: 'MATERIALI UTILI',
        kankulator: 'Calcolatrice di capacità',
        buket: 'Libretto del gioco',
        accaunt: 'Account',
        buy: 'Acquistare',
        sale: 'Già in vendita',
        buys: 'Acquistare',
        treyler: 'TREYLER',
        change: 'It',
        en: 'Inglese',
        ru: 'Russia',
        de: 'Tedesca',
        po: 'Polacca',
        pr: 'portoghese (BR)',
        fr: 'francese',
        es: 'Spangola',
        esp: 'Spangola (MX)',
        it: 'Italiana',
        ja: 'giapponese',
        ko: 'Coreana',
        ch: 'Cinese s',
        chs: 'Cinese t',
        ar: 'Araba',
        open: 'APRIRE',
        free: 'Gioca gratis',
        firstinput: 'Inserisci la tua email',
        secondinput: 'password',
        recovery: 'Reimposta password',
        create: 'creare un account',
        popuptitle: 'creare un account',
        option: 'Scegli la lingua...',
        mailinput: 'E-mail',
        nameinput: 'Nome',
        textpasswordss: 'password',
        surnameinput: 'Cognome',
        returnname: 'Nome da visualizzare',
        radiop: 'Inviami notizie, sondaggi e offerte speciali da Cybernet Games',
        radiopp: 'Ho letto e accetto i termini di servizio',
        radiolink: 'termini di servizio',
        submitbtn: 'continuare',
        popupt: 'Reimposta password',
        conectp: `Per ricevere un codice di sicurezza, inserisci l'indirizzo email del tuo account Cybernet Games`,
        openss: 'continuare',
        loginbutton: 'torna alla pagina di accesso',
        successMessage: 'Riuscita!',
        fillFields: 'Si prega di compilare tutti i campi.',
    },
    ja: {
        greeting: "ゲーム",
        fravel: 'サイバーパンク2077',
        fravel2: 'ファントムフリーダム',
        community: 'コミュニティ',
        forum: 'フォーラム',
        discord: '不和',
        material: '役に立つ資料',
        kankulator: '能力計算機',
        buket: 'ゲームブックレット',
        accaunt: 'アカウント',
        buy: '買う',
        sale: 'すでに販売中',
        buys: '買う',
        treyler: 'トレイラー',
        change: '日本語',
        en: '英語',
        ru: 'ロシア',
        de: 'ドイツ語',
        po: '研磨',
        pr: 'ポルトガル語（BR）',
        fr: 'フランス語',
        es: 'スペイン語',
        esp: 'スペイン語 (MX)',
        it: 'イタリア語',
        ja: '日本語',
        ko: '韓国語',
        ch: '中国語（簡体字）',
        chs: '繁体字中国語',
        ar: 'アラビア語',
        open: '開ける',
        free: '無料でプレイ',
        firstinput: 'メールアドレスを入力してください',
        secondinput: 'パスワード',
        recovery: 'パスワードをリセット',
        create: 'アカウントを作成する',
        popuptitle: 'アカウントを作成する',
        option: '言語を選択してください...',
        mailinput: '電子メール',
        nameinput: '名前',
        textpasswordss: 'パスワード',
        surnameinput: '姓',
        returnname: '表示名',
        radiop: 'Cypernet Gamesからのニュース、アンケート、特別オファーを受け取る',
        radiopp: '利用規約を読み、同意します',
        radiolink: '利用規約',
        submitbtn: '続く',
        popupt: 'パスワードをリセット',
        conectp: 'セキュリティコードを受け取るには、Cypernet Gamesアカウントのメールアドレスを入力してください。',
        openss: '続く',
        loginbutton: 'ログインページに戻る',
        successMessage: '成功！',
        fillFields: 'すべてのフィールドに入力してください。',
    },
    ko: {
        greeting: "게임",
        fravel: '사이버펑크 2077',
        fravel2: '팬텀 프리덤',
        community: '지역 사회',
        forum: '법정',
        discord: '불화',
        material: '유용한 자료',
        kankulator: '능력 계산기',
        buket: '게임 소책자',
        accaunt: '계정',
        buy: '구입하다',
        sale: '이미 판매중입니다',
        buys: '구입하다',
        treyler: '트레이러',
        change: '한국어',
        en: '영어',
        ru: '러시아 제국',
        de: '독일 사람',
        po: '광택',
        pr: '포르투갈어(BR)',
        fr: '프랑스 국민',
        es: '스페인 사람',
        esp: '스페인 사람 (MX)',
        it: '이탈리아 사람',
        ja: '일본어',
        ko: '한국인',
        ch: '간체 중국어',
        chs: '중국어 번체',
        ar: '아라비아 말',
        open: '열려 있는',
        free: '무료로 플레이하세요',
        firstinput: '이메일을 입력하세요',
        secondinput: '비밀번호',
        recovery: '비밀번호 재설정',
        create: '계정을 생성하다',
        popuptitle: '계정을 생성하다',
        option: '언어를 선택하세요...',
        mailinput: '이메일',
        nameinput: '이름',
        textpasswordss: '비밀번호',
        surnameinput: '성',
        returnname: '표시 이름',
        radiop: 'Cypernet Games의 뉴스, 설문 조사 및 특별 행사를 보내주세요.',
        radiopp: '서비스 약관을 읽었고 동의합니다.',
        radiolink: '서비스 약관',
        submitbtn: '계속하다',
        popupt: 'Reset password',
        conectp: '보안 코드를 받으려면 Cypernet Games 계정의 이메일 주소를 입력하세요.',
        openss: '계속하다',
        loginbutton: '로그인 페이지로 돌아가기',
        successMessage: '성공적인!',
        fillFields: '모든 항목을 입력해 주세요.',
    },
    zhCn: {
        greeting: "游戏",
        fravel: '赛博朋克 2077',
        fravel2: '幻影自由',
        community: '社区',
        forum: '论坛',
        discord: '不和谐',
        material: '有用资料',
        kankulator: '能力计算器',
        buket: '游戏手册',
        accaunt: '帐户',
        buy: '买',
        sale: '已开始销售',
        buys: '买',
        treyler: '特雷勒', 
        change: '简体中文',
        en: '英语',
        ru: '俄罗斯',
        de: '德语',
        po: '抛光',
        pr: '葡萄牙语 （巴西）',
        fr: '法语',
        es: '西班牙语',
        esp: '西班牙语',
        it: '意大利语',
        ja: '日本人',
        ko: '韩国人',
        ch: '简体中文',
        chs: '繁体中文',
        ar: '阿拉伯',
        open: '打开',
        free: '免费畅玩',
        firstinput: '输入您的电子邮件',
        secondinput: '输入您的密码',
        recovery: '重置密码',
        create: '创建一个帐户',
        popuptitle: '创建一个帐户',
        option: '选择语言...',
        mailinput: '电子邮件',
        nameinput: '姓名',
        textpasswordss: '密码',
        surnameinput: '姓',
        returnname: '显示名称',
        radiop: '向我发送 Cypernet Games 的新闻、调查和特别优惠',
        radiopp: '我已阅读并接受服务条款',
        radiolink: '服务条款',
        submitbtn: '继续',
        popupt: '重置密码',
        conectp: '要接收安全代码，请输入您的 Cypernet Games 帐户的电子邮件地址',
        openss: '继续',
        loginbutton: '返回登录页面',
        successMessage: '成功的！!',
        fillFields: '请填写所有字段。',
    },
    zhtw: {
        greeting: "游戏",
        fravel: '赛博朋克 2077',
        fravel2: '幻影自由',
        community: '社区',
        forum: '论坛',
        discord: '不和谐',
        material: '有用资料',
        kankulator: '能力计算器',
        buket: '游戏手册',
        accaunt: '帐户',
        buy: '买',
        sale: '已开始销售',
        buys: '买',
        treyler: '特雷勒',
        change: '繁體中文',
        en: '英語',
        ru: '俄羅斯',
        de: '德文',
        po: '拋光',
        pr: '葡萄牙語（巴西）',
        fr: '法語',
        es: '西班牙語',
        esp: '西班牙語 (MX)',
        it: '義大利語',
        ja: '日本人',
        ko: '韓國人',
        ch: '簡體中文',
        chs: '繁體中文',
        ar: '阿拉伯',
        open: '打开',
        free: '免费畅玩',
        firstinput: '输入您的电子邮件',
        secondinput: '输入您的密码',
        recovery: '重置密码',
        create: '创建一个帐户',
        popuptitle: '创建一个帐户',
        option: '选择语言...',
        mailinput: '电子邮件',
        nameinput: '姓名',
        textpasswordss: '密码',
        surnameinput: '姓',
        returnname: '显示名称',
        radiop: '向我发送 Cypernet Games 的新闻、调查和特别优惠',
        radiopp: '我已阅读并接受服务条款',
        radiolink: '服务条款',
        submitbtn: '继续',
        popupt: '重置密码',
        conectp: '要接收安全代码，请输入您的 Cypernet Games 帐户的电子邮件地址',
        openss: '继续',
        loginbutton: '返回登录页面',
        successMessage: '成功的！',
        fillFields: '请填写所有字段。',
    },
    ar: {
        greeting: "لعبة",
        fravel: 'السايبربانك 2077',
        fravel2: 'الحرية الشبحية',
        community: 'مجتمع',
        forum: 'المنتدى',
        discord: 'الخلاف',
        material: 'مواد مفيدة',
        kankulator: 'حاسبة القدرة',
        buket: 'كتيب اللعبة',
        accaunt: 'حساب',
        buy: 'يشتري',
        sale: 'معروض للبيع بالفعل',
        buys: 'يشتري',
        treyler: 'تريلر',
        change: 'العربية',
        en: 'إنجليزي',
        ru: 'روسيا',
        de: 'الألمانية',
        po: 'بولندي',
        pr: 'البرتغالية (البرازيل)',
        fr: 'فرنسي',
        es: 'الأسبانية',
        esp: 'الإسبانية (المكسيك)',
        it: 'ايطالي',
        ja: 'اليابانية',
        ko: 'كوري',
        ch: 'الصينية المبسطة',
        chs: 'الصينية التقليدية',
        ar: 'عربي',
        open: 'يفتح',
        free: 'العب مجانا',
        firstinput: 'أدخل بريدك الإلكتروني',
        secondinput: 'أدخل كلمة المرور الخاصة بك',
        recovery: 'إعادة تعيين كلمة المرور',
        create: 'إنشاء حساب',
        popuptitle: 'إنشاء حساب',
        option: 'اختر اللغة...',
        mailinput: 'بريد إلكتروني',
        nameinput: 'اسم',
        textpasswordss: 'كلمة المرور',
        surnameinput: 'اسم العائلة',
        returnname: 'اسم العرض',
        radiop: 'أرسل لي الأخبار والاستطلاعات والعروض الخاصة من Cypernet Games',
        radiopp: 'لقد قرأت ووافقت على شروط الخدمة',
        radiolink: 'شروط الخدمة',
        submitbtn: 'يكمل',
        popupt: 'إعادة تعيين كلمة المرور',
        conectp: 'لتلقي رمز الأمان، يرجى إدخال عنوان البريد الإلكتروني لحساب Cypernet Games الخاص بك',
        openss: 'يكمل',
        loginbutton: 'العودة إلى صفحة تسجيل الدخول',
        successMessage: 'ناجح!',
        fillFields: 'يرجى ملء جميع الحقول.',
    }
};

let currentLanguage = 'ru';

function setLanguage(lang) {
    currentLanguage = lang;
    updateUI();
}

function updateUI() {
    document.getElementById('greeting').innerText = translations[currentLanguage].greeting;
    document.querySelector('.greeting').innerText = translations[currentLanguage].greeting;
    document.getElementById('farewell').innerHTML = translations[currentLanguage].fravel;
    document.querySelector('.farewell').innerHTML = translations[currentLanguage].fravel;
    document.getElementById('fravel2').innerHTML = translations[currentLanguage].fravel2;
    document.querySelector('.fravel2').innerHTML = translations[currentLanguage].fravel2;
    document.getElementById('community').innerHTML = translations[currentLanguage].community;
    document.querySelector('.community').innerHTML = translations[currentLanguage].community;
    document.getElementById('forum').innerHTML = translations[currentLanguage].forum;
    document.querySelector('.forum').innerHTML = translations[currentLanguage].forum;
    document.getElementById('discord').innerHTML = translations[currentLanguage].discord;
    document.querySelector('.discord').innerHTML = translations[currentLanguage].discord;
    document.getElementById('material').innerHTML = translations[currentLanguage].material;
    document.querySelector('.material').innerHTML = translations[currentLanguage].material;
    document.getElementById('kankulator').innerHTML = translations[currentLanguage].kankulator;
    document.querySelector('.kankulator').innerHTML = translations[currentLanguage].kankulator;
    document.getElementById('buket').innerHTML = translations[currentLanguage].buket;
    document.querySelector('.buket').innerHTML = translations[currentLanguage].buket;
    document.getElementById('accaunt').innerHTML = translations[currentLanguage].accaunt;
    document.querySelector('.accaunt').innerHTML = translations[currentLanguage].accaunt;
    document.getElementById('buy').innerHTML = translations[currentLanguage].buy;
    document.querySelector('.buy').innerHTML = translations[currentLanguage].buy;
    document.getElementById('sale').innerHTML = translations[currentLanguage].sale;
    document.getElementById('buys').innerHTML = translations[currentLanguage].buys;
    document.getElementById('treyler').innerHTML = translations[currentLanguage].treyler;
    document.getElementById('change').innerHTML = translations[currentLanguage].change;
    document.getElementById('changes').innerHTML = translations[currentLanguage].change;
    document.getElementById('en').innerHTML = translations[currentLanguage].en;
    document.getElementById('enn').innerHTML = translations[currentLanguage].en;
    document.getElementById('ru').innerHTML = translations[currentLanguage].ru;
    document.getElementById('rus').innerHTML = translations[currentLanguage].ru;
    document.getElementById('de').innerHTML = translations[currentLanguage].de;
    document.getElementById('deu').innerHTML = translations[currentLanguage].de;
    document.getElementById('po').innerHTML = translations[currentLanguage].po;
    document.getElementById('pol').innerHTML = translations[currentLanguage].po;
    document.getElementById('pr').innerHTML = translations[currentLanguage].pr;
    document.getElementById('prr').innerHTML = translations[currentLanguage].pr;
    document.getElementById('fr').innerHTML = translations[currentLanguage].fr;
    document.getElementById('fra').innerHTML = translations[currentLanguage].fr;
    document.getElementById('es').innerHTML = translations[currentLanguage].es;
    document.getElementById('ess').innerHTML = translations[currentLanguage].es;
    document.getElementById('esp').innerHTML = translations[currentLanguage].esp;
    document.getElementById('esps').innerHTML = translations[currentLanguage].esp;
    document.getElementById('it').innerHTML = translations[currentLanguage].it;
    document.getElementById('ita').innerHTML = translations[currentLanguage].it;
    document.getElementById('ja').innerHTML = translations[currentLanguage].ja;
    document.getElementById('jap').innerHTML = translations[currentLanguage].ja;
    document.getElementById('ko').innerHTML = translations[currentLanguage].ko;
    document.getElementById('kor').innerHTML = translations[currentLanguage].ko;
    document.getElementById('ch').innerHTML = translations[currentLanguage].ch;
    document.getElementById('chi').innerHTML = translations[currentLanguage].ch;
    document.getElementById('chs').innerHTML = translations[currentLanguage].chs;
    document.getElementById('chss').innerHTML = translations[currentLanguage].chs;
    document.getElementById('ar').innerHTML = translations[currentLanguage].ar;
    document.getElementById('ara').innerHTML = translations[currentLanguage].ar;
    document.getElementById('open').innerHTML = translations[currentLanguage].open;
    document.getElementById('opens').innerHTML = translations[currentLanguage].open;
    document.getElementById('free').innerHTML = translations[currentLanguage].free;
    document.getElementById('freez').innerHTML = translations[currentLanguage].free;
    document.getElementById('frees').innerHTML = translations[currentLanguage].free;
    document.getElementById('textgmail').placeholder = translations[currentLanguage].firstinput;
    document.getElementById('textpassword').placeholder = translations[currentLanguage].secondinput;
    document.getElementById('textpasswordss').placeholder = translations[currentLanguage].secondinput;
    document.getElementById('recovery').innerHTML = translations[currentLanguage].recovery;
    document.getElementById('createAccount').innerHTML = translations[currentLanguage].create;
    document.getElementById('popuptitle').innerHTML = translations[currentLanguage].popuptitle;
    document.getElementById('mailinput').placeholder = translations[currentLanguage].mailinput;
    document.getElementById('radiopteg').innerHTML = translations[currentLanguage].radiop;
    document.getElementById('radiopp').innerHTML = translations[currentLanguage].radiopp;
    document.getElementsByClassName('radiolink').innerHTML = translations[currentLanguage].radiolink;
    document.getElementById('submitbtn').innerHTML = translations[currentLanguage].submitbtn;
    document.getElementById('popupt').innerHTML = translations[currentLanguage].popupt;
    document.getElementById('conectp').innerHTML = translations[currentLanguage].conectp;
    document.getElementById('openss').innerHTML = translations[currentLanguage].openss;
    document.getElementById('loginbutton').innerHTML = translations[currentLanguage].loginbutton;
    document.getElementById('textgmails').placeholder = translations[currentLanguage].mailinput;
    document.getElementById('textpaswordss').placeholder = translations[currentLanguage].returninput;
    document.getElementById('connectp').innerHTML = translations[currentLanguage].connectp;
    document.getElementById('surnameinput').placeholder = translations[currentLanguage].surnameinput;
}

window.onload = updateUI;